"""initial fall_events table

Revision ID: dd4ac95e70c8
Revises: 
Create Date: 2026-03-14 17:32:44.820691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd4ac95e70c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fall_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('image_path', sa.String(length=1024), nullable=False),
    sa.Column('fall_detected', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('needs_immediate_attention', sa.Boolean(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fall_events')
    # ### end Alembic commands ###
